name: echo-ai

channels:
    - anaconda
    - pytorch

dependencies:
    - python==3.7
    - pytorch
    - pip:
        - matplotlib
        - absl-py==0.7.1
        - astor==0.8.0
        - cycler==0.10.0
        - future==0.17.1
        - gast==0.2.2
        - google-pasta==0.1.7
        - grpcio==1.21.1
        - h5py==2.9.0
        - joblib==0.13.2
        - Keras==2.2.4
        - Keras-Applications==1.0.8
        - Keras-Preprocessing==1.1.0
        - kiwisolver==1.1.0
        - Markdown==3.1.1
        - numpy==1.16.4
        - protobuf==3.8.0
        - pyparsing==2.4.0
        - python-dateutil==2.8.0
        - pytz==2019.1
        - PyYAML==5.1.1
        - scipy==1.3.0
        - tensorflow==1.14.0
        - tensorflow-estimator==1.14.0
        - termcolor==1.1.0
        - Werkzeug==0.15.4
        - wrapt==1.11.2
